server:
  port: 8030
spring:
  application:
    name: user-service
eureka:
  instance:
    hostname: localhost  
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka
